config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root to: "home#index"
  
  get 'home/index'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'


  #либо get 'contacts' => 'contacts#new'
  resource :contacts, only: [:new, :create], path_names: {:new => ''} #resorce - метод, который принимаем символ и хеш. Используем только методы new и create на стр.
  resources :articles do
    resources :comments, only: :create 
  end   #Если сущность одна, то resource. А если собираемся использовать несколько сущностей, то resources(много экземпляров сущности)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {maximum: 140}
  validates :text, presence: true, length: {maximum: 4000}

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, length: {maximum: 4000}
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render action: 'new' #можно использовать redirect_to, но потеряеся переменная @article, то есть render не прерывает запрос
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.order('created_at DESC')
  end
             
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end
  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end
  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def terms
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(resource)
    root_path # or any other path # Решает проблему с маршрутом sign up, после добавляем маршрут с контроллером
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/articles/create.html.erb
<h1>Thanks!</h1>
<p>Article has been created</p>

<%= link_to 'Show all articles!', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<% if @article && @article.errors.any? %>
		<p>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</p>
	<% end %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>

	</p>
	<p>
		<%= f.label :text %><br />
		<%= f.text_area :text %>
		
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/index.html.erb
<h1>Articles:</h1>
<br />
<% @articles.each do |art| %>
	<p>
		<h3><%= art.title %></h3>
		<br />
		<%= art.text %>
		<br />
		<br />
		<span style="font-size: 75%; color: #999;">Added at <%= art.created_at %></span>
	</p>
	
	<p>
		<%= link_to 'Show', article_path(art) %> |
		<%= link_to 'Edit', edit_article_path(art) %> |
		<%= button_to 'Delete', article_path(art), method: :delete, data: {'turbo-confirm': 'Are you sure?'} %> <!--  link_to 'Delete', article_path(art), data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } -->
	</p>
	<hr />
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for :article, url: '/articles', data: { turbo: false } do |f| %>
	<% if @article && @article.errors.any? %>
		<p>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</p>
	<% end %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>

	</p>
	<p>
		<%= f.label :text %><br />
		<%= f.text_area :text %>
		
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
	<%= @article.text %>
</p>
<br />


<% @article.comments.each do |comment| %>
	<h3>Comments:</h3>
	<p>
		<i><h4><%= comment.author %></h4></i>
		<br />
		<i><%= comment.body %></i>
		<br />
		<br />
		<span style="font-size: 75%; color: #999;">At <%= comment.created_at %></span>
	</p>
	<hr />
<% end %>

<p>
	<h4>Write your comment!</h4>
	<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :author %><br />
		<%= f.text_field :author %>
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.text_field :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	<% end %>
</p>

app/views/contacts/create.html.erb
<p>Thanks!</p>

app/views/contacts/new.html.erb
<h1><%= t("contacts.contact_us") %></h1>

<%= form_for :contact, url: contacts_path, data: {turbo: false} do |f| %>
	<% if @contact && @contact.errors.any? %>
		<p>
			<ul>
				<% @contact.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</p>
	<% end %>
	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>

	</p>
	<p>
		<%= f.label :message %><br />
		<%= f.text_area :message %>
		
	</p>
	<p>
		<%= f.submit 'Send message' %>
	</p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" %>
    <script src=https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>

    Hello, <%= current_user.username %> | <%= link_to "Log out", destroy_user_session_path, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?'} %>

    <% else %>

    <%= link_to "Log in", new_user_session_path %> 

    <% end %>

    

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/terms.html.erb
<h1>Terms of Service</h1>